# ============================================================
# backend/ml/ai_image_detector.py
#
# AI-Generated Image Detection
# ─────────────────────────────
# Detects if an image is generated by AI or authentic
# Uses multiple detection techniques designed to catch AI images
# ============================================================

import logging
from pathlib import Path
from typing import Dict, Any
import numpy as np
from PIL import Image
from PIL.ExifTags import TAGS

logger = logging.getLogger(__name__)


def check_synth_id(image_path: str) -> Dict[str, Any]:
    """
    Comprehensive AI image detection using multiple techniques.
    
    Returns dict with:
    - is_ai_generated: bool
    - confidence: float (0-1)
    - markers_found: list of detected AI markers
    - details: detailed explanation
    """
    markers_found = []
    scores = {
        'metadata': 0.0,
        'artifacts': 0.0,
        'statistics': 0.0,
        'texture': 0.0,
        'anomaly': 0.0,
    }
    
    try:
        img = Image.open(image_path)
        
        # ── Check metadata ──────────────────────────────────────
        meta_score, meta_markers = check_metadata(img)
        markers_found.extend(meta_markers)
        scores['metadata'] = meta_score
        
        # ── Convert to RGB for analysis ────────────────────────
        if img.mode != 'RGB':
            img = img.convert('RGB')
        
        pixels = np.array(img, dtype=np.float32)
        
        if pixels.size == 0:
            raise ValueError("Image is empty")
        
        # ── Analyze artifacts ──────────────────────────────────
        artifact_score, artifact_markers = analyze_artifacts(pixels)
        markers_found.extend(artifact_markers)
        scores['artifacts'] = artifact_score
        
        # ── Statistical analysis ───────────────────────────────
        stat_score, stat_markers = analyze_statistics(pixels)
        markers_found.extend(stat_markers)
        scores['statistics'] = stat_score
        
        # ── Texture analysis ───────────────────────────────────
        texture_score, texture_markers = analyze_texture(pixels)
        markers_found.extend(texture_markers)
        scores['texture'] = texture_score
        
        # ── Anomaly detection ──────────────────────────────────
        anomaly_score, anomaly_markers = detect_anomalies(pixels, img.size)
        markers_found.extend(anomaly_markers)
        scores['anomaly'] = anomaly_score
        
        # ── Calculate weighted confidence ───────────────────────
        # More aggressive weighting
        ai_confidence = (
            scores['metadata'] * 0.25 +
            scores['artifacts'] * 0.25 +
            scores['statistics'] * 0.20 +
            scores['texture'] * 0.15 +
            scores['anomaly'] * 0.15
        )
        
        # Add bonus if multiple categories detect AI
        categories_detecting = sum(1 for score in scores.values() if score > 0.3)
        if categories_detecting >= 2:
            ai_confidence += 0.15
        
        if categories_detecting >= 3:
            ai_confidence += 0.2
        
        ai_confidence = min(ai_confidence, 1.0)
        
    except Exception as e:
        logger.error(f"Error checking image: {e}")
        return {
            "is_ai_generated": False,
            "confidence": 0.0,
            "markers_found": [f"Analysis error: {str(e)}"],
            "details": f"Could not fully analyze image: {str(e)}"
        }
    
    # ── Decision logic ──────────────────────────────────────
    # Much lower threshold - flag as AI if confidence > 0.15
    is_ai_generated = ai_confidence > 0.15
    
    details = generate_details(is_ai_generated, ai_confidence, markers_found, scores)
    
    return {
        "is_ai_generated": is_ai_generated,
        "confidence": round(ai_confidence, 2),
        "markers_found": markers_found if markers_found else ["Insufficient data for conclusive analysis"],
        "details": details
    }


def check_metadata(img: Image.Image) -> tuple:
    """Check for AI markers in image metadata."""
    score = 0.0
    markers = []
    
    ai_keywords = [
        'generated', 'synthetic', 'ai', 'model', 'latent', 'diffusion', 'gan',
        'midjourney', 'dall-e', 'dalle', 'stable diffusion', 'stabilityai',
        'gemini', 'claude', 'gpt', 'google', 'openai', 'anthropic',
        'suno', 'udio', 'runway', 'synthesis', 'ai generated'
    ]
    
    try:
        exif = img.getexif()
        if exif:
            for tag_id, value in exif.items():
                value_str = str(value).lower()
                for keyword in ai_keywords:
                    if keyword in value_str:
                        markers.append(f"Metadata contains '{keyword}'")
                        score += 0.3
        
        if hasattr(img, 'info') and img.info:
            for key, value in img.info.items():
                value_str = str(value).lower()
                for keyword in ai_keywords:
                    if keyword in value_str:
                        markers.append(f"Found '{keyword}' in image info")
                        score += 0.3
    except:
        pass
    
    return min(score, 1.0), markers


def analyze_artifacts(pixels: np.ndarray) -> tuple:
    """Detect AI generation artifacts in pixel data."""
    markers = []
    score = 0.0
    
    try:
        # ── Check color channel uniformity ──────────────────────
        # AI images often have suspiciously similar color channels
        r = pixels[:, :, 0]
        g = pixels[:, :, 1]
        b = pixels[:, :, 2]
        
        r_var = np.var(r)
        g_var = np.var(g)
        b_var = np.var(b)
        
        # If all channels have very similar variance, likely AI
        channel_variance_std = np.std([r_var, g_var, b_var])
        if channel_variance_std < 50:
            markers.append("Unnormally uniform color channels")
            score += 0.25
        
        # ── Check for excessive smoothness ─────────────────────
        gray = np.mean(pixels, axis=2)
        
        # Calculate Laplacian (edge detection)
        laplacian = np.zeros_like(gray)
        if gray.shape[0] > 2 and gray.shape[1] > 2:
            for i in range(1, gray.shape[0] - 1):
                for j in range(1, gray.shape[1] - 1):
                    laplacian[i, j] = abs(
                        4 * gray[i, j] - 
                        gray[i-1, j] - gray[i+1, j] - 
                        gray[i, j-1] - gray[i, j+1]
                    )
            
            laplacian_mean = np.mean(laplacian)
            
            # AI images have either very low (over-smoothed) or very high edge content
            if laplacian_mean < 5:
                markers.append("Excessive smoothness (over-processed)")
                score += 0.2
        
        # ── Check for noise characteristics ────────────────────
        # Real photos have natural noise; AI images often lack it
        if len(pixels) > 10 and len(pixels[0]) > 10:
            # Sample noise from different regions
            noise_samples = []
            for i in range(0, len(pixels) - 10, len(pixels) // 3):
                for j in range(0, len(pixels[0]) - 10, len(pixels[0]) // 3):
                    region = gray[i:i+10, j:j+10]
                    noise = np.std(region)
                    noise_samples.append(noise)
            
            if noise_samples:
                avg_noise = np.mean(noise_samples)
                noise_consistency = np.std(noise_samples)
                
                # AI images have very consistent, artificial noise patterns
                if avg_noise < 3:
                    markers.append("Abnormally low noise floor")
                    score += 0.15
                
                if noise_consistency < 0.5 and avg_noise > 0:
                    markers.append("Unnaturally consistent noise pattern")
                    score += 0.15
        
        # ── Check saturation levels ────────────────────────────
        # Convert to HSV to check saturation
        from PIL import Image as PILImage
        pil_img = PILImage.fromarray(np.uint8(pixels))
        hsv = pil_img.convert('HSV')
        hsv_array = np.array(hsv, dtype=np.float32)
        
        saturation = hsv_array[:, :, 1]
        avg_sat = np.mean(saturation)
        sat_std = np.std(saturation)
        
        # AI images often have too-uniform or too-high saturation
        if avg_sat > 200 or sat_std < 20:
            markers.append("Suspicious saturation pattern")
            score += 0.15
        
    except Exception as e:
        logger.warning(f"Artifact analysis error: {e}")
    
    return min(score, 1.0), markers


def analyze_statistics(pixels: np.ndarray) -> tuple:
    """Analyze statistical properties of the image."""
    markers = []
    score = 0.0
    
    try:
        gray = np.mean(pixels, axis=2)
        
        # ── Check histogram distribution ────────────────────────
        hist, _ = np.histogram(gray, bins=256, range=(0, 256))
        
        # Real photos have relatively smooth histograms
        # AI images often have gaps or unusual peaks
        hist_smoothness = np.std(hist)
        
        if hist_smoothness > 500:  # Very spiky histogram
            markers.append("Abnormal histogram distribution")
            score += 0.15
        
        # ── Check entropy ──────────────────────────────────────
        # AI images often have lower complexity
        hist_normalized = hist / np.sum(hist)
        hist_normalized = hist_normalized[hist_normalized > 0]
        entropy = -np.sum(hist_normalized * np.log2(hist_normalized))
        
        if entropy < 6:  # Unusually low
            markers.append("Low image entropy (AI characteristic)")
            score += 0.2
        
        # ── Check dynamic range ────────────────────────────────
        # AI images often don't use full dynamic range
        min_val = np.min(gray)
        max_val = np.max(gray)
        dynamic_range = max_val - min_val
        
        if dynamic_range < 150:
            markers.append("Limited dynamic range")
            score += 0.15
        
        # ── Check for mean shift ────────────────────────────────
        # AI images often have brighter means
        mean_val = np.mean(gray)
        
        if mean_val > 200:
            markers.append("Unusually bright mean (common in AI)")
            score += 0.1
        
    except Exception as e:
        logger.warning(f"Statistics analysis error: {e}")
    
    return min(score, 1.0), markers


def analyze_texture(pixels: np.ndarray) -> tuple:
    """Analyze texture properties."""
    markers = []
    score = 0.0
    
    try:
        gray = np.mean(pixels, axis=2)
        
        # ── Local contrast analysis ────────────────────────────
        # AI images lack natural local contrast variation
        if gray.shape[0] > 16 and gray.shape[1] > 16:
            contrast_map = np.zeros((gray.shape[0] - 8, gray.shape[1] - 8))
            
            for i in range(gray.shape[0] - 8):
                for j in range(gray.shape[1] - 8):
                    patch = gray[i:i+8, j:j+8]
                    contrast = np.std(patch)
                    contrast_map[i, j] = contrast
            
            # Check if contrast is too uniform
            contrast_std = np.std(contrast_map)
            if contrast_std < 10:
                markers.append("Unnaturally uniform local contrast")
                score += 0.2
        
        # ── Edge distribution ──────────────────────────────────
        # Calculate edges using simple gradient
        gy, gx = np.gradient(gray)
        edges = np.sqrt(gx**2 + gy**2)
        
        edge_mean = np.mean(edges)
        edge_std = np.std(edges)
        
        # AI images often have consistent edge patterns
        if edge_mean > 0:
            edge_cv = edge_std / edge_mean
            if edge_cv < 0.3:  # Too consistent
                markers.append("Suspiciously consistent edge patterns")
                score += 0.15
        
    except Exception as e:
        logger.warning(f"Texture analysis error: {e}")
    
    return min(score, 1.0), markers


def detect_anomalies(pixels: np.ndarray, size: tuple) -> tuple:
    """Detect anomalous properties typical of AI images."""
    markers = []
    score = 0.0
    
    try:
        width, height = size
        
        # ── Check for AI-typical dimensions ────────────────────
        ai_sizes = [
            (512, 512), (768, 768), (1024, 1024),
            (512, 768), (768, 512), (1024, 576), (576, 1024),
            (1024, 1365), (1365, 1024),  # Common ratios
        ]
        
        for w, h in ai_sizes:
            if (width, height) in [(w, h), (h, w)]:
                markers.append(f"Standard AI output size: {width}x{height}")
                score += 0.15
                break
        
        # ── Check for perfect aspect ratios ────────────────────
        aspect_ratios = [1.0, 16/9, 9/16, 4/3, 3/4, 1.5, 0.67]
        aspect = width / max(height, 1)
        
        for ratio in aspect_ratios:
            if abs(aspect - ratio) < 0.03:
                markers.append(f"Perfect aspect ratio {ratio}:1")
                score += 0.12
                break
        
        # ── Check for power-of-2 dimensions ────────────────────
        if (width & (width - 1)) == 0 and (height & (height - 1)) == 0:
            markers.append("Both dimensions are powers of 2")
            score += 0.15
        
        # ── Color space analysis ───────────────────────────────
        r_mean = np.mean(pixels[:, :, 0])
        g_mean = np.mean(pixels[:, :, 1])
        b_mean = np.mean(pixels[:, :, 2])
        
        # Check if channels are suspiciously balanced
        channel_diffs = [abs(r_mean - g_mean), abs(g_mean - b_mean), abs(r_mean - b_mean)]
        
        if np.mean(channel_diffs) < 5:
            markers.append("Suspiciously balanced RGB channels")
            score += 0.15
        
    except Exception as e:
        logger.warning(f"Anomaly detection error: {e}")
    
    return min(score, 1.0), markers


def generate_details(is_ai_generated: bool, confidence: float, markers: list, scores: dict) -> str:
    """Generate detailed analysis report."""
    
    if is_ai_generated:
        if confidence > 0.7:
            verdict = "⚠️ HIGHLY LIKELY AI-GENERATED"
        elif confidence > 0.5:
            verdict = "⚠️ LIKELY AI-GENERATED"
        else:
            verdict = "⚠️ POSSIBLY AI-GENERATED"
        
        details = f"{verdict}\nConfidence: {int(confidence * 100)}%\n\n"
        details += "🔍 Detection Summary:\n"
        
        for category, score_val in scores.items():
            if score_val > 0.1:
                bar_len = int(score_val * 20)
                bar = "█" * bar_len + "░" * (20 - bar_len)
                details += f"  {category.capitalize():12} [{bar}] {int(score_val*100)}%\n"
        
        details += "\n📋 Detected Markers:\n"
        for marker in markers[:8]:
            details += f"  • {marker}\n"
        
        details += "\n⚠️ This image appears to be AI-generated.\n"
        details += "Exercise caution when sharing or using as evidence."
    else:
        details = "✅ LIKELY AUTHENTIC IMAGE\n"
        details += f"Confidence: {int((1 - confidence) * 100)}%\n\n"
        details += "No significant AI generation markers detected.\n"
        details += "This appears to be a genuine photograph."
    
    return details


async def analyze_image_file(file_path: str) -> Dict[str, Any]:
    """Main async function to analyze an image file."""
    try:
        result = check_synth_id(file_path)
        return {
            "status": "success",
            "is_ai_generated": result["is_ai_generated"],
            "confidence": result["confidence"],
            "markers": result["markers_found"],
            "details": result["details"]
        }
    except Exception as e:
        logger.error(f"Image analysis error: {e}")
        return {
            "status": "error",
            "error": str(e),
            "is_ai_generated": False,
            "confidence": 0.0
        }


